---
packages:
- kubeadm
- kubectl
- kubelet

master_node_ip: x.x.x.x 
worker_node_ips:
  - x.x.x.y
  - x.x.x.z

http_proxy: <http_proxy>
https_proxy: <https_proxy>
no_proxy: 127.0.0.1,10.96.0.*,10.244.0/16,x.x.x.x,x.x.x.y,x.x.x.z,<ARRAY_IPs>

hosts_names:
  - x.x.x.y    node-1
  - x.x.x.z    node-2

nodes:
  node-1: x.x.x.y
  node-2: x.x.x.z
